<?php foreach ($listing as $list) { 

$arr = array('jenis_trans' => $list->jenis_transaksi, 
			 'alamat_properti' => $list->alamat_properti, 
			 'kode_pos' => $list->kode_pos, 
			 'kelurahan' => $list->kelurahan, 
			 'kecamatan' => $list->kecamatan,
			 'tipe_properti' => $list->tipe_properti,
			 'luas_tanah' => $list->luas_tanah, 
			 'luas_bangunan' => $list->luas_bangunan,
			 'orientasi' => $list->orientasi,
			 'tingkat' => $list->tingkat, 
			 'kamar_tidur' => $list->kamar_tidur,
			 'kamar_mandi' => $list->kamar_mandi,
			 'rlain' => $list->ruangan_lain, 
			 'listrik' => $list->listrik,
			 'telepon' => $list->telepon,
			 'ac' => $list->ac, 
			 'air' => $list->air,
			 'flain' => $list->fasilitas_lain, 
			 'gambar' => $list->gambar, 
			 'status_milik' => $list->status_kepemilikan,
			 'nama_penjual' => $list->nama_penjual,
			 'alamat_penjual' => $list->alamat_penjual, 
			 'email_penjual' => $list->email_penjual, 
			 'status_kawin_penjual' => $list->status_kawin_penjual,
			 'notelp' => $list->no_telepon_penjual, 
			 'no_hp_penjual' => $list->no_hp_penjual,
			 'nama_disertif' => $list->nama_disertifikat,
			 'waktu_kosong' => date("j-M-y", strtotime($list->waktu_pengosongan)),
			 'harga_permintaan' => $list->harga_permintaan,
			 'hargamin' => $list->harga_minimal,
			 'tawar_akhir' => $list->penawaran_terakhir,
			 'tanggal' => date("j-M-y", strtotime($list->tanggal)),
			 'namawakil' => $list->nama_perwakilan,
			 'kodemarketing' => $list->kode_marketing,
			 'namamanager' => $list->nama_manager,
			 );
echo json_encode($arr);

 } ?>